version: '2'
services:
  web-client:
    image: node:6.5.0
    expose:
      - "3000"
    volumes:
      - ./web-client:/usr/src/app
      - ./assets:/usr/src/app/assets
    command: "/bin/bash -c \"cd /usr/src/app && npm install && npm start\""
    depends_on:
      - web-api
  web-api:
    image: node:6.5.0
    enviroment:
      - PG_HOST='postgres'
    expose:
      - "3001"
    volumes:
      - ./web-api:/usr/src/app
      - ./assets:/usr/src/app/assets
    command: "/bin/bash -c \"cd /usr/src/app && npm run build && npm run start\""
    depends_on:
      - postgres
  postgres:
    image: postgres
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  nginx:
    image: nginx
    ports:
      - "3000:3000"
    volumes:
      - ./nginx/nginx-prod.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-api
      - web-client
