version: '2'
services:
  web-client:
    image: node:6.5.0
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
      - ./web-client:/usr/src/app
      - ./assets:/usr/src/app/assets
    command: "/bin/bash -c \"cd /usr/src/app && npm install && npm run build:dll && npm start\""
    depends_on:
      - web-api
  web-api:
    image: node:6.5.0
    network_mode: host
    environment:
      - PG_HOST=localhost
    ports:
      - "3001:3001"
    volumes:
      - ./web-api:/usr/src/app
      - ./assets:/usr/src/app/assets
    command: "/bin/bash -c \"cd /usr/src/app && npm install && npm run build && npm run init && npm run start\""
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres
    network_mode: host
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    network_mode: host
  survey-training-preprocessor:
    image: python:3.5
    network_mode: host
    volumes:
      - ./assets:/usr/src/app/assets
      - ./okcollege-survey-training-preprocessor:/usr/src/app
    command: "/bin/bash -c \"cd /usr/src/app && pip install -r requirements.txt && python preprocessor.py\""
    depends_on:
      - postgres
      - redis
  nginx:
    image: nginx
    network_mode: host
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-client
      - web-api
